version: "3.9"  # optional since v1.27.0
services:
 front-end:
  build: ./frontEnd/ngRaffle
  ports:
   - 3000:80
   # Host:Container
  depends_on:
   - back-end

 back-end:
  build: ./backEnd
  ports:
   - 4200:4200
 
  environment:
   - PORT=4200
   - CONNECTIONSTRING=mongodb://raffle-admin:password@mongo-db:27017
   - ACCESS_TOKEN_SECRET=85f3fe0d2f2c8181abd8ec129bbc3b285b44266e1fec1c9c9545febdd14079ed686bc72c26d801d16c7c296150c1675aa86ef3db0a220b037f8c50bd1599d613
   - REFRESH_TOKEN_SECRET=5205be0d6b6c734249d00ffe414abc0d274961e3ef412248b235fc21d6c6662cb2b56bd7e77b918872f6b8f6a96c403eb09091cdbdf018897fc90d8a6b5130c5
   - RAFFLE_CODE_TOTAL=50000
   - RAFFLE_CODE_LENGTH=12
   - RAFFLE_CATEGORIES={"A":10,"B":500,"C":1000,"D":20000}
   - MAX_DAILY_CHECK=3
   - GOOGLE_CLIENT_ID=273481175043-ufdcirqms6ooj4f15lqundib5u0e99nc.apps.googleusercontent.com
   - GOOGLE_CLIENT_SECRET=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
   - GOOGLE_REFRESH_TOKEN=1//04hKV5R_Wr7psCgYIARAAGAQSNgF-L9IrPSDMH7d-sYDIzUwbDOz18tD2bI-zcN4Xoa13c3quBcO4_Fwb9_jLAjVlKF9IVZQssQ
   - MAIlER_USER=donotreply@pneumatictech.com
   - MAIlER_RECIPIENT=obiora.obi@pneumatictech.com,obichukwu.obi@gmail.com

  volumes:
   - gen-files:/app/repo
  depends_on:
   - mongo-db

 mongo-db:
  image: mongo
  ports:
   - 27017:27017
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: raffle-admin
   ME_CONFIG_MONGODB_ADMINPASSWORD: password
  volumes:
   - ./dbscripts/:/docker-entrypoint-initdb.d/:ro
   - db-data:/data/db

 mongo-express:
  image: mongo-express
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_BASICAUTH_USERNAME: raffle-admin
   ME_CONFIG_BASICAUTH_PASSWORD: password
   ME_CONFIG_MONGODB_SERVER: mongo-db
  depends_on:
   - mongo-db

volumes:
 gen-files: {}
 db-data: {}
